########################################################

INCLUDE=\
	-I"$(ROOT)/Code/Modules"\
	-I"$(ROOT)/Code/Modules/mutant"\

CC_FLAGS=\
	-Wno-unused\

SRCS = $(wildcard *.c)
SRCS+= $(wildcard *.cpp)
SRCS+= $(wildcard psp/*.cpp)

include ../../build.mak
